LPS-113426 portal-search-test-util: Removing usage of DocumentImpl to prevent java.lang.NoClassDefFoundError: Could not initialize class GroupByTest
Caused by LPS-84440 liferay-portal-ee@5120d8ab206997900eb562a242e34f7e0279f007

https://issues.liferay.com/browse/LPS-113426