LPS-113426 portal-search-elasticsearch: Bump version of "org.ow2.asm" dependencies to 5.0.4 to fix
com.liferay.portal.search.elasticsearch.internal.groupby.GroupByTest > testGroupByDocsStart FAILED
    java.lang.RuntimeException: Unable to create snapshot class for interface com.liferay.portal.search.elasticsearch.configuration.ElasticsearchConfiguration
        at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._createConfigurableSnapshot(ConfigurableUtil.java:81)
(...)
        Caused by:
        java.lang.NoSuchMethodError: org.objectweb.asm.MethodVisitor.visitMethodInsn(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
            at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._generateSnapshotClassData(ConfigurableUtil.java:147)
            at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._createConfigurableSnapshot(ConfigurableUtil.java:68)
            ... 54 more

when running com.liferay.portal.search.elasticsearch.internal.groupby.GroupByTest.

This is because portal-configuration-metatype uses 5.0.4, while 4.1 used by portal-search-elasticsearch currently does not have this method in MethodVisitor.

https://issues.liferay.com/browse/LPS-113426